version: '3.8'
services:
  dev-db:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DATABASE}'
    networks:
      - pm-backend

  redis: 
    image: redis:5.0
    restart: always   
    ports: 
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks: 
      - pm-backend

volumes:
  postgres_data:
  redis_data:

networks:
  pm-backend:
